### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by sugarshin**
Added package.json, please npm resister.

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks, will see to this soon!

**Comment by sugarshin** [comment]
@alexgibson Thanks! please publishes a package to the npm registry!

**Comment by alexgibson** [comment]
Here you go, sorry for delay https://www.npmjs.com/package/shake.js

**Comment by sugarshin** [comment]
@alexgibson Thank you :+1:

**Pull request merged**
