### PR TITLE
Fix define global object for module loader

### PR DESCRIPTION
**Pull request by sugarshin**
When the module load, global object is empty. case using the Browserify. This code that has been used even jQuery

### CODE REVIEW

**Comment by alexgibson** [comment]
Can you please add a better description for what you are fixing here, I want to try and understand what's not working, given that this patters is from https://github.com/umdjs/umd

**Comment by sugarshin** [comment]
For details, check it because it does not know. Sorry, I'm not good at much English.

**Comment by alexgibson** [comment]
Found relevant commit, thanks: https://github.com/jquery/jquery/commit/6de1d973a436282af7dfe3072924016c3cdc1984#diff-f1ebe0c2ce0a72c9131e854556761642

**Comment by alexgibson** [comment]
Tested with Browserify and this does fix the issue, thanks @sugarshin!

**Comment by alexgibson** [comment]
https://github.com/alexgibson/shake.js/releases/tag/v1.2.1

**Comment by sugarshin** [comment]
Thank you ask them to the verification!

**Pull request merged**
